name: Xmake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: grub-pc-bin xorriso mtools nasm
        version: 1.0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2

    - name: Setup BuildTools
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: '.xmake-cache'
        
    - name: Build Kernel
      run: xmake build -y
        
    - uses: actions/upload-artifact@v4
      with:
        name: Bootable ISO
        path: build/mdros.iso
        compression-level: 9