name: Xmake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: XmakeBuild
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: ilammy/setup-nasm@v1
    - uses: goto-bus-stop/setup-zig@v2

    - name: APT Dependencies
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: grub-pc-bin xorriso mtools

    - name: Setup BuildTools
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: '.xmake-cache'
      run: |
        apt install xorriso
        apt install 
        
    - name: Build Kernel
      run: |
        xmake build -y
# uses: softprops/action-gh-release@v2 # 自动上传到release
